---
title: "pageRank"
author: "Steve Zhang"
date: "July 11, 2017"
output: html_document
---

```{r}
library(expm)
```

```{r}
M = matrix(c(0, 1/3, 1/3, 1/3, 0.5, 0, 0, 0.5, 1, 0, 0, 0, 0, 0.5, 0.5, 0), nrow = 4)
```

```{r}
finalDist = function(mat, T = 50) {
    n = dim(mat)[1]
    v = matrix(rep(1/n, n), nrow = n)
    return((mat %^% T) %*% v)
}
```

```{r}
v = matrix(c(rep(0.25, 4)), nrow = 4)
finalDist(M, v)
```

```{r}
trapRank = function(mat, beta = 0.8, r = 50) {
    n = dim(mat)[1]
    ranks = matrix(rep(1/n, n), nrow = n)
    e = matrix(rep(1, n), nrow = n)
    for (i in 1:r) {
        ranks = ((beta *M) %*% ranks) + (1- beta)*e/n
    }
    return(ranks)
}
```

```{r}
L = matrix(c(0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0), nrow = 5)
L
```

```{r}
hits = function(L, max.iter = 100, eps = 0.001) {
    n = dim(L)[1]
    h = matrix(rep(1, n), nrow = n)
    iterations = 0
    for (i in 1:max.iter) {
        iterations = iterations + 1
        a = t(L) %*% h
        a = a / max(a)
        h = L %*% a
        h = h / max(h)
    }
    cat("Iterations needed for convergence:", iterations, "\n")
    cat("Authority:", a, "\n")
    cat("Hub:", h, "\n")
}
```

